### ISSUE TITLE
Error on export to Excel

### ISSUE THREAD

**Issue by Jercyvz** [rzinguer/AccessSecurityRoles#1]
Hello. Thanks for the plugin. But there is an error when I try to export results to Excel.

Here is the error text.

_System.Runtime.InteropServices.COMException (0x8002000B): Неверный индекс. (Исключение из HRESULT: 0x8002000B (DISP_E_BADINDEX))
   в Microsoft.Office.Interop.Excel.Sheets.get__Default(Object Index)
   в AccessSecurityRole.AccessSecurityRole.btn_Export_Click(Object sender, EventArgs e)
   в System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   в System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)_

If you need any additional information, let me know.

Thanks!
Regards,
Evgeniy.

**Comment by rzinguer** [comment]
Evgeniy, thank you very much for identifying this issue.
The code has been updated and published in a new version 1.2020.9.12
Please, let me know if you still experience the same error.

**Comment by Jercyvz** [comment]
Thanks a lot for the fast resolving.
You mean to 1.2020.9.11 ?
![image](https://user-images.githubusercontent.com/29932591/95593869-e0cc1800-0a52-11eb-8441-9d038c43d46a.png)

**Comment by Jercyvz** [comment]
> Evgeniy, thank you very much for identifying this issue.
> The code has been updated and published in a new version 1.2020.9.12
> Please, let me know if you still experience the same error.

Error was gone with the new version! Thanks a lot!!!
